[[header]]
  name = "About"
  url = "/about/"
  weight = 1
[[header]]
  name = "Research"
  url = "/research/"
  weight = 2
[[header]]
  name = "Missions"
  url = "/missions/"
  weight = 3
[[header]]
  name = "Projects"
  url = "/project/"
  weight = 4
[[header]]
  name = "Publications"
  url = "/publication/"
  weight = 5
[[header]]
  name = "Talks"
  url = "/talk/"
  weight = 6
[[header]]
  name = "Blog"
  url = "/blog/"
  weight = 7
[[header]]
  name = "CV"
  url = "/cv/"
  weight = 8

[[footer]]
  name = "Collaborate"
  url = "/collaborate/"
  weight = 1
[[footer]]
  name = "Contact"
  url = "/contact/"
  weight = 2
